input_format: profdata
coverage_service: cobertura_xml
workspace: ShapeSwift.xcworkspace
xcodeproj: ShapeSwift.xcodeproj
scheme: ShapeSwift
source_directory: ShapeSwift
output_directory: tmp
ignore:
  - Pods/*
  - ShapeSwiftTests/*
