language: Objective-C
osx_image: xcode8
install:
  - bundle install --without=documentation --path ../travis_bundle_dir
  - bundle exec pod install
script: xcodebuild -workspace ShapeSwift.xcworkspace -scheme ShapeSwift -destination 'platform=iOS Simulator,name=iPhone 6s' test CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO
after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f tmp/cobertura.xml
