language: Objective-C
osx_image: xcode10.1
env:
  - NSUnbufferedIO=YES
before_install:
  - bundle install --with ci --without=documentation --path vendor
install:
  - bundle exec pod install
script: xcodebuild -workspace ShapeSwift.xcworkspace -scheme ShapeSwift -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone SE' -enableCodeCoverage YES test

after_failure:
  - sleep 10

after_success:
  - bundle exec slather
  - bash <(curl -s https://codecov.io/bash) -f tmp/cobertura.xml
