language: Objective-C
osx_image: xcode8
xcode_workspace: ShapeSwift.xcworkspace
xcode_scheme: ShapeSwift
env:
  - NSUnbufferedIO=YES
before_install: ./scripts/travis/prep_keychain.sh
install:
  - bundle install --without=documentation --path ../travis_bundle_dir
  - bundle exec pod install
after_success: 
  - slather
  - bash <(curl -s https://codecov.io/bash) -f tmp/cobertura.xml
